-- -----------------------------------------------------
-- Data for table `booking_db`.`cities`
-- -----------------------------------------------------
START TRANSACTION;
USE `booking_db`;
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('An Giang');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bà Rịa - Vũng Tàu');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bắc Giang');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bắc Kạn');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bạc Liêu');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bắc Ninh');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bến Tre');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bình Định');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bình Dương');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bình Phước');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Bình Thuận');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Cà Mau');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Cao Bằng');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Đắk Lắk');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Đắk Nông');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Điện Biên');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Đồng Nai');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Đồng Tháp');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Gia Lai');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hà Giang');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hà Nam');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hà Tĩnh');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hải Dương');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hậu Giang');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hoà Bình');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hưng Yên');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Khánh Hoà');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Kiên Giang');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Kon Tum');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Lai Châu');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Lâm Đồng');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Lạng Sơn');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Lào Cai');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Long An');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Nam Định');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Nghệ An');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Ninh Bình');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Ninh Thuận');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Phú Thọ');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Quảng Bình');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Quảng Nam');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Quảng Ngãi');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Quảng Ninh');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Quảng Trị');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Sóc Trăng');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Sơn La');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Tây Ninh');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Thái Bình');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Thái Nguyên');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Thanh Hoá');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Thừa Thiên Huế');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Tiền Giang');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Trà Vinh');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Tuyên Quang');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Vĩnh Long');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Vĩnh Phúc');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Yên Bái');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Phú Yên');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Cần Thơ');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Thừa Thiên Huế');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Đà Nẵng');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hải Phòng');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Hà Nội');
INSERT INTO `booking_db`.`cities` (`name`) VALUES ('Thành phố Hồ Chí Minh');

COMMIT;